name: Java CI with Maven

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: List test results
        run: ls -al target/surefire-reports/

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

  e2e:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Cucumber Tests
        run: mvn test -PE2E cluecumber:reporting

      - name: Upload Cluecumber Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cluecumber-report
          path: target/generated-report

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Cucumber Tests
          path: target/cucumber-reports/*.xml
          reporter: java-junit
          fail-on-error: true

  e2eFailure:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Run Cucumber Failure Tests
        run: mvn test -PE2E -DtestngFile="src/test/resources/failureTestNG.xml" cluecumber:reporting

      - name: Upload Cluecumber Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: cluecumber-report
          path: target/generated-report

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Cucumber Failure Tests
          path: target/cucumber-reports/*.xml
          reporter: java-junit
          fail-on-error: true
